# Generated by Django 3.0 on 2019-12-21 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='currencyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main_app.Currency'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currencyid',
            field=models.ForeignKey(on_delete=models.SET(1), related_name='wallets', to='main_app.Currency'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='userid',
            field=models.ForeignKey(on_delete=models.SET(1), related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
    ]
