# Generated by Django 3.0 on 2019-12-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191221_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
